export default class Hobby {
  static HOB_OPTIONS = [
    [1, "映画", "hobby_movie.webp"],
    [2, "カラオケ", "hobby_karaoke.webp"],
    [3, "写真", "hobby_camera.webp"],
    [4, "劇場", "hobby_theater.webp"],
    [5, "芸術", "hobby_art.webp"],
    [6, "音楽", "hobby_music.webp"],
    [7, "創作", "hobby_creator.webp"],
    [8, "ゲーム", "hobby_gaming.webp"],
    [9, "アニメ", "hobby_anime.webp"],
    [10, "小説", "hobby_book.webp"],
    [11, "旅行", "hobby_travel.webp"],
    [12, "運動", "hobby_exercise.webp"],
    [13, "ジョギング", "hobby_jogging.webp"],
    [14, "車", "hobby_car.webp"],
    [15, "自転車", "hobby_bicycle.webp"],
    [16, "ダンス", "hobby_dance.webp"],
    [17, "ゴルフ", "hobby_golf.webp"],
    [18, "ダーツ", "hobby_dart.webp"],
    [19, "格闘技", "hobby_boxing.webp"],
    [20, "トレーニング", "hobby_fitness.webp"],
    [21, "結婚", "hobby_wedding.webp"],
    [22, "スイーツ", "hobby_sweet.webp"],
    [23, "料理", "hobby_cook.webp"],
    [24, "インドア", "hobby_indoor.webp"],
    [25, "動物", "hobby_norway.webp"],
    [26, "お笑い", "hobby_owarai.webp"],
    [27, "雑貨", "hobby_zakka.webp"],
    [28, "ハイキング", "hobby_mountain.webp"],
    [29, "温泉", "hobby_onsen.webp"],
    [30, "遊園地", "hobby_ferris-wheel.webp"],
    [31, "アルコール", "hobby_alchool.webp"],
    [32, "お喋り", "hobby_talk.webp"],
  ];
}
