export default class Interests {
  static INT_OPTIONS = [
    [1, "食品・農林・水産", "interest_agriculture.webp"],
    [2, "建設・住宅・インテリア", "interest_construction.webp"],
    [3, "繊維・化学・薬品・化粧品", "interest_fiber.webp"],
    [4, "鉄鋼・金属・鉱業", "interest_steel.webp"],
    [5, "機械・プラント", "interest_plant.webp"],
    [6, "電子・電気機器", "interest_electric.webp"],
    [7, "自動車・輸送用機器", "interest_vehicle.webp"],
    [8, "精密・医療機器", "interest_medical.webp"],
    [9, "印刷・事務機器関連", "interest_clerical.webp"],
    [10, "スポーツ・玩具", "interest_sports.webp"],
    [11, "その他メーカー", "interest_otherMaker.webp"],
    [12, "不動産", "interest_estate.webp"],
    [13, "鉄道・航空・運輸・物流", "interest_logistics.webp"],
    [14, "電力・ガス・エネルギー", "interest_energy.webp"],
    [15, "フードサービス", "interest_food.webp"],
    [16, "ホテル・旅行", "interest_hotel.webp"],
    [17, "医療・福祉", "interest_welfare.webp"],
    [18, "アミューズメント・レジャー", "interest_leisure.webp"],
    [19, "その他サービス業", "interest_otherService.webp"],
    [20, "コンサルティング・調査", "interest_consulting.webp"],
    [21, "人材サービス", "interest_human.webp"],
    [22, "教育", "interest_education.webp"],
    [23, "総合商社", "interest_generalTrading.webp"],
    [24, "専門商社", "interest_specializedTrading.webp"],
    [25, "ソフトウェア", "interest_software.webp"],
    [26, "インターネット", "interest_internet.webp"],
    [27, "通信", "interest_communication.webp"],
    [28, "百貨店・スーパー", "interest_department.webp"],
    [29, "コンビニ", "interest_convenience.webp"],
    [30, "専門店", "interest_specialty.webp"],
    [31, "放送", "interest_broadcast.webp"],
    [32, "新聞", "interest_newspaper.webp"],
    [33, "出版", "interest_publication.webp"],
    [34, "広告", "interest_advertisement.webp"],
    [35, "銀行・証券", "interest_bank.webp"],
    [36, "クレジット", "interest_credit.webp"],
    [37, "信販・リース", "interest_lease.webp"],
    [38, "その他金融", "interest_otherFinance.webp"],
    [39, "生保・損保", "interest_insurance.webp"],
    [40, "公社・団体", "interest_group.webp"],
    [41, "官公庁", "interest_government.webp"],
  ];
}
