export default class Interests {
  static INT_OPTIONS = [
    [1, "食品・農林・水産", "hobby_movie.jpg"],
    [2, "建設・住宅・インテリア", "hobby_movie.jpg"],
    [3, "繊維・化学・薬品・化粧品", "hobby_movie.jpg"],
    [4, "鉄鋼・金属・鉱業", "hobby_movie.jpg"],
    [5, "機械・プラント", "hobby_movie.jpg"],
    [6, "電子・電気機器", "hobby_movie.jpg"],
    [7, "自動車・輸送用機器", "hobby_movie.jpg"],
    [8, "精密・医療機器", "hobby_movie.jpg"],
    [9, "印刷・事務機器関連", "hobby_movie.jpg"],
    [10, "スポーツ・玩具", "hobby_movie.jpg"],
    [11, "その他メーカー", "hobby_movie.jpg"],
    [12, "不動産", "hobby_movie.jpg"],
    [13, "鉄道・航空・運輸・物流", "hobby_movie.jpg"],
    [14, "電力・ガス・エネルギー", "hobby_movie.jpg"],
    [15, "フードサービス", "hobby_movie.jpg"],
    [16, "ホテル・旅行", "hobby_movie.jpg"],
    [17, "医療・福祉", "hobby_movie.jpg"],
    [18, "アミューズメント・レジャー", "hobby_movie.jpg"],
    [19, "その他サービス業", "hobby_movie.jpg"],
    [20, "コンサルティング・調査", "hobby_movie.jpg"],
    [21, "人材サービス", "hobby_movie.jpg"],
    [22, "教育", "hobby_movie.jpg"],
    [23, "総合商社", "hobby_movie.jpg"],
    [24, "専門商社", "hobby_movie.jpg"],
    [25, "ソフトウェア", "hobby_movie.jpg"],
    [26, "インターネット", "hobby_movie.jpg"],
    [27, "通信", "hobby_movie.jpg"],
    [28, "百貨店・スーパー", "hobby_movie.jpg"],
    [29, "コンビニ", "hobby_movie.jpg"],
    [30, "専門店", "hobby_movie.jpg"],
    [31, "放送", "hobby_movie.jpg"],
    [32, "新聞", "hobby_movie.jpg"],
    [33, "出版", "hobby_movie.jpg"],
    [34, "広告", "hobby_movie.jpg"],
    [35, "銀行・証券", "hobby_movie.jpg"],
    [36, "クレジット", "hobby_movie.jpg"],
    [37, "信販・リース", "hobby_movie.jpg"],
    [38, "その他金融", "hobby_movie.jpg"],
    [39, "生保・損保", "hobby_movie.jpg"],
    [40, "公社・団体", "hobby_movie.jpg"],
    [41, "官公庁", "hobby_movie.jpg"]
  ];
}


