export default class Interests {
  static INT_OPTIONS = [
    [1, "食品・農林・水産", "interest_agriculture.jpg"],
    [2, "建設・住宅・インテリア", "interest_construction.jpg"],
    [3, "繊維・化学・薬品・化粧品", "interest_fiber.jpg"],
    [4, "鉄鋼・金属・鉱業", "interest_steel.jpg"],
    [5, "機械・プラント", "interest_plant.jpg"],
    [6, "電子・電気機器", "interest_electric.jpg"],
    [7, "自動車・輸送用機器", "interest_vehicle.jpg"],
    [8, "精密・医療機器", "interest_medical.jpg"],
    [9, "印刷・事務機器関連", "interest_clerical.jpg"],
    [10, "スポーツ・玩具", "interest_sports.jpg"],
    [11, "その他メーカー", "interest_otherMaker.jpg"],
    [12, "不動産", "interest_estate.jpg"],
    [13, "鉄道・航空・運輸・物流", "interest_logistics.jpg"],
    [14, "電力・ガス・エネルギー", "interest_energy.jpg"],
    [15, "フードサービス", "interest_food.jpg"],
    [16, "ホテル・旅行", "interest_hotel.jpg"],
    [17, "医療・福祉", "interest_welfare.jpg"],
    [18, "アミューズメント・レジャー", "interest_leisure.jpg"],
    [19, "その他サービス業", "interest_otherService.jpg"],
    [20, "コンサルティング・調査", "interest_consulting.jpg"],
    [21, "人材サービス", "interest_human.jpg"],
    [22, "教育", "interest_education.jpg"],
    [23, "総合商社", "interest_generalTrading.jpg"],
    [24, "専門商社", "interest_specializedTrading.jpg"],
    [25, "ソフトウェア", "interest_software.jpg"],
    [26, "インターネット", "interest_internet.jpg"],
    [27, "通信", "interest_communication.jpg"],
    [28, "百貨店・スーパー", "interest_department.jpg"],
    [29, "コンビニ", "interest_convenience.jpg"],
    [30, "専門店", "interest_specialty.jpg"],
    [31, "放送", "interest_broadcast.jpg"],
    [32, "新聞", "interest_newspaper.jpg"],
    [33, "出版", "interest_publication.jpg"],
    [34, "広告", "interest_advertisement.jpg"],
    [35, "銀行・証券", "interest_bank.jpg"],
    [36, "クレジット", "interest_credit.jpg"],
    [37, "信販・リース", "interest_lease.jpg"],
    [38, "その他金融", "interest_otherFinance.jpg"],
    [39, "生保・損保", "interest_insurance.jpg"],
    [40, "公社・団体", "interest_group.jpg"],
    [41, "官公庁", "interest_government.jpg"],
  ];
}
