databases:
  - name: mysite
    databaseName: mysite
    user: mysite_production_cn5u_user
    region: Oregon

services:
  - type: web
    name: mysite
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

